CONTPAQI/CONTPAQI.Web/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using CONTPAQI.BusinessLogic;
using CONTPAQI.Entities;
using CONTPAQI.Web.Common;
using log4net;

namespace CONTPAQI.Web.Models
{
    public class EmpresasController : Controller
    {
        private static readonly log4net.ILog _log = Logs.GetLogger();
        private readonly IEmpresaBL _empresaBL;

        public EmpresasController(IEmpresaBL empresaBL)
        {
            _empresaBL = empresaBL;
        }

        // GET: Empresas
        public ActionResult Index()
        {
            //var empresas = new EmpresaBL().ObtenerEmpresas(null);
            var empresas = _empresaBL.ObtenerEmpresas(null);
            return View(empresas);
        }

        // GET: Empresas/Create
        public ActionResult Create()
        {
            return View(new Empresa());
        }

        // POST: Empresas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Empresa empresa)
        {
            try
            {
                //throw new Exception("Error forzado!");
                if (ModelState.IsValid)
                {
                    empresa.IDEmpresa = 0;
                    empresa.Activo = true;
                    empresa.Borrado = false;
                    empresa.FechaCreacion = DateTime.Now;
                    empresa.UsuarioCreador = "sistemas";

                    //new EmpresaBL().GrabarEmpresa(empresa);
                    _empresaBL.GrabarEmpresa(empresa);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception exception)
            {
                _log.Error(exception.Message);
                ModelState.AddModelError("", "La empresa no se ha guardado, favor de revisarlo con su administrador de sistemas.");
            }

            return View(empresa);
        }

        // GET: Empresas/Edit/5
        public ActionResult Edit(int idEmpresa)
        {
            //var empresa = new EmpresaBL().ObtenerEmpresas(idEmpresa).FirstOrDefault();
            var empresa = _empresaBL.ObtenerEmpresas(idEmpresa).FirstOrDefault();
            return View(empresa);
        }

        // POST: Empresas/Edit/5
        [HttpPost]
        public ActionResult Edit(int idEmpresa, Empresa empresa)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    empresa.FechaUltAct = DateTime.Now;
                    empresa.UsuarioUltAct = "sistemas";

                    //new EmpresaBL().GrabarEmpresa(empresa);
                    _empresaBL.GrabarEmpresa(empresa);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception exception)
            {
                _log.Error(exception.Message);
                ModelState.AddModelError("", "La empresa no se ha actualizado, favor de revisarlo con su administrador de sistemas.");
            }

            return View(empresa);
        }

        // GET: Empresas/Delete/5
        public ActionResult Delete(int idEmpresa)
        {
            //var empresa = new EmpresaBL().ObtenerEmpresas(idEmpresa).FirstOrDefault();
            var empresa = _empresaBL.ObtenerEmpresas(idEmpresa).FirstOrDefault();
            return View(empresa);
        }

        // POST: Empresas/Delete/5
        [HttpPost]
        public ActionResult Delete(int idEmpresa, Empresa empresa)
        {
            try
            {
                empresa.Activo = false;
                empresa.Borrado = true;
                empresa.FechaUltAct = DateTime.Now;
                empresa.UsuarioUltAct = "sistemas";

                //new EmpresaBL().EliminarEmpresa(empresa);
                _empresaBL.EliminarEmpresa(empresa);
                return RedirectToAction("Index");
            }
            catch (Exception exception)
            {
                _log.Error(exception.Message);
                ModelState.AddModelError("", "La empresa no se ha eliminado, favor de revisarlo con su administrador de sistemas.");
            }

            return View(empresa);
        }
    }
}

CONTPAQI/CONTPAQI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CONTPAQI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CONTPAQI/CONTPAQI.Web/Controllers/YahooController.cs
using CONTPAQI.Entities;
using CONTPAQI.Web.Common;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CONTPAQI.Web.Controllers
{
    public class YahooController : Controller
    {
        private static readonly log4net.ILog _log = Logs.GetLogger();
        private readonly string _apiRESTYahoo = ConfigurationManager.AppSettings["APIRestYahoo"];
        private readonly string _tokenYahoo = ConfigurationManager.AppSettings["TokenYahoo"];

        // GET: Yahoo
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public async Task<ActionResult> Index()
        {
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_apiRESTYahoo);
                    client.DefaultRequestHeaders.Clear();
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    client.DefaultRequestHeaders.Add("x-api-key", _tokenYahoo);
                    HttpResponseMessage response = await client.GetAsync("/v6/finance/quote?region=US&lang=en&symbols=AAPL%2CBTC-USD%2CEURUSD%3DX");
                    
                    var json = response.Content.ReadAsStringAsync().Result;
                    var quote = JsonConvert.DeserializeObject<Root>(json).QuoteResponse.Quote;
                    return View(quote);
                }
            }
            catch (Exception exception)
            {
                _log.Error(exception.Message);
                return View();
            }
        }
    }
}

CONTPAQI/CONTPAQI.Web/Views/Empresas/Create.cshtml
@model CONTPAQI.Entities.Empresa

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Empresa</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RFC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RFC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Municipio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Calle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Calle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Calle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumeroInterior, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroInterior, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumeroInterior, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumeroExterior, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroExterior, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumeroExterior, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Colonia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Colonia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Colonia, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CONTPAQI/CONTPAQI.Web/Views/Empresas/Delete.cshtml
@model CONTPAQI.Entities.Empresa

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar Empresa</h2>

<h3>¿Esta seguro que desea eliminar esta Empresa?</h3>
<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.IDEmpresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDEmpresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RazonSocial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RFC)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RFC)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Municipio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroInterior)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroInterior)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroExterior)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroExterior)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Colonia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Colonia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Borrado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Borrado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioCreador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioCreador)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaUltAct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaUltAct)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UsuarioUltAct)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UsuarioUltAct)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

CONTPAQI/CONTPAQI.Web/Views/Empresas/Edit.cshtml
@model CONTPAQI.Entities.Empresa

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Empresa</h4>
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.IDEmpresa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDEmpresa, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.IDEmpresa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RazonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RazonSocial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RazonSocial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RFC, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RFC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Pais, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Pais, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Pais, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Municipio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Calle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Calle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Calle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumeroInterior, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroInterior, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumeroInterior, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NumeroExterior, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NumeroExterior, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NumeroExterior, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Colonia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Colonia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Colonia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Activo)
                @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Borrado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Borrado)
                @Html.ValidationMessageFor(model => model.Borrado, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CONTPAQI/CONTPAQI.Web/Views/Empresas/Index.cshtml
@model IEnumerable<CONTPAQI.Entities.Empresa>

@{
    ViewBag.Title = "Empresa";
}

<h2>Empresas</h2>

<p>
    @Html.ActionLink("Crear Empresa", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDEmpresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RazonSocial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RFC)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Municipio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroInterior)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroExterior)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Colonia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Borrado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UsuarioCreador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaUltAct)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UsuarioUltAct)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IDEmpresa)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RazonSocial)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RFC)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Pais)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Estado)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Municipio)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Calle)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NumeroInterior)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NumeroExterior)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Colonia)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Activo)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Borrado)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaCreacion)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UsuarioCreador)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaUltAct)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UsuarioUltAct)
    </td>
    <td>
        @Html.ActionLink("Editar", "Edit", new { idEmpresa = item.IDEmpresa }) |
        @Html.ActionLink("Eliminar", "Delete", new { idEmpresa = item.IDEmpresa })
    </td>
</tr>
}

</table>

CONTPAQI/CONTPAQI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CONTPAQI/CONTPAQI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CONTPAQI/CONTPAQI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CONTPAQI/CONTPAQI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CONTPAQI</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CONTPAQI", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Empresas", "Index", "Empresas")</li>
                    <li>@Html.ActionLink("Yahoo Finace Quote", "Index", "Yahoo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - CONTPAQI</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>